### PR TITLE
Add diagrams for find

### PR DESCRIPTION
**Pull request by tantzeyeong**

### CODE REVIEW

**Comment by ongwenpin** [comment]
Arrow when going from findcommand to StudentContainsKeywordPredicate, TutorContainsKeywordPredicate and TuitionClassContainsKeywordPredicate need to be full line instead of dashed line.

**Comment by tantzeyeong** [comment]
> Arrow when going from findcommand to StudentContainsKeywordPredicate, TutorContainsKeywordPredicate and TuitionClassContainsKeywordPredicate need to be full line instead of dashed line.

Fixed!

**Comment by ongwenpin** [comment]
Arrow for when going from logiccommand to commandresult need to be bold. Sorry didnt see it earlier

**Comment by ongwenpin** [comment]
LGTM!

**Pull request merged**
